Allow skipping of the download for the binary
chronotc/monorepo-diff-buildkite-plugin pull request #69
Opened 2021-07-22 22:44 UTC by rajatvig

An attempt to address the [issue](https://github.com/chronotc/monorepo-diff-buildkite-plugin/issues/68).
If anything is missing, can address.

2021-07-27 23:14 UTC, rajatvig commented
Would anyone be looking at this? Is the commit fine?

2021-08-02 22:19 UTC, rajatvig commented
@chronotc @adikari Could you please take a look?

2021-08-05 03:34 UTC, adikari commented
Hi @rajatvig, I appreciate the PR but please go through the [contributing guide](https://github.com/chronotc/monorepo-diff-buildkite-plugin/blob/master/CONTRIBUTING.md) first. 

I quickly looked into the PR and it generally looks good. I would like to understand the problem you are trying to solve and how it will benefit others who are using the plugin. 

Thanks

2021-08-05 12:40 UTC, rajatvig commented
Thanks for looking into it. Had raised an issue - https://github.com/chronotc/monorepo-diff-buildkite-plugin/issues/68 - for it.

The problem that this PR solves is the need to download the binary every pipeline run which takes time. We are also concerned about security so downloading binaries at build time is not preferable and instead we would prefer to keep the binary included as part of the buildkite agent just like the `buildkite-agent` binary.

2021-08-13 09:16 UTC, rajatvig commented
@adikari Could you please when you have time look at the PR? Can make any adjustments as required.

2021-09-16 15:04 UTC, adikari requested changes
This looks good. Happy to merge this once the config option name is changed.

2021-09-16 15:04 UTC, adikari commented on plugin.yml
> +    download:
I am thinking maybe we should call this option `downloadBinary` to be more descriptive.

2021-09-16 15:04 UTC, adikari commented on README.md
> +By setting `download` to `false`, the plugin assumes that the binary is present in `/usr/bin`.
It would be useful to add use case on when you might one to use this config? Similar to the one you have mentioned on the PR comment.

2021-09-16 15:08 UTC, adikari commented
It would be nice if you could also update the test to include the new property https://github.com/chronotc/monorepo-diff-buildkite-plugin/blob/master/tests/command.bats#L96

2021-10-20 06:31 UTC, adikari commented
@rajatvig any updates on the PR?

2022-02-08 05:58 UTC, closed without merging